### ISSUE TITLE
Incorrect error message when trying to move job across file systems

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#148]
### Description

As reported by @rosecers, trying to move a job between file systems using the `job.move()` function fails internally with `OSError: [Errno 18] Invalid cross-device link: `, however signac reports a  `signac.contrib.errors.DestinationExistsError`, because of too coarse exception handling.

### To reproduce

Move a job between different file systems.

### Error output

```
Traceback (most recent call last):
  File "/home/rosecers/.local/lib/python3.5/site-packages/signac/contrib/job.py", line 391, in move
    os.rename(self.workspace(), dst.workspace())
OSError: [Errno 18] Invalid cross-device link: 'REDACTED' -> 'REDACTED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "operations.py", line 524, in <module>
    flow.run()
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/operations.py", line 194, in run
    operation(job)
  File "operations.py", line 513, in move
    job.move(other_project)
  File "/home/rosecers/.local/lib/python3.5/site-packages/signac/contrib/job.py", line 393, in move
    raise DestinationExistsError(dst)
signac.contrib.errors.DestinationExistsError: 17adbd4ffbcaf50566f885b366a773d0
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: n/a
 - Version of Python [e.g. 3.7]: n/a
 - Version of signac [e.g. 1.0]: n/a

**Comment by csadorf** [comment]
Fixed with merge of PR #149 .
