### ISSUE TITLE
Using get_project() with a relative path and search=False fails

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#191]
### Description

Using the `signac.get_project()` or `signac.Project.get_project()` functions with a relative path and `search=False` argument fails even if the path contains a valid project configuration.
### To reproduce

```python
import signac
signac.init_project('test', 'test-project')
signac.get_project('.')  # works
signac.get_project('.'), search=False)  # raises LookupError
```

### Error output

```
Traceback (most recent call last):
  File "project-search-bug.py", line 4, in <module>
    project = signac.get_project('.', search=False)
  File "/Users/csadorf/local/signac/signac/contrib/project.py", line 1876, in get_project
    return Project.get_project(root=root, search=search)
  File "/Users/csadorf/local/signac/signac/contrib/project.py", line 1500, in get_project
    "Unable to determine project id for path '{}'.".format(os.path.abspath(root)))
LookupError: Unable to determine project id for path '/Users/csadorf/my_project'.
```

### System configuration

```
Darwin-15.6.0-x86_64-i386-64bit
3.7.2 (default, Dec 29 2018, 00:00:04)
[Clang 4.0.1 (tags/RELEASE_401/final)]
1.0.0
```

**Comment by csadorf** [comment]
Resolved with merge of PR #192 .
