### ISSUE TITLE
Schema fails for non-sortable values within lists

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac#209]
### Description

The schema detection fails when the data space contains jobs with state point values **within a list or tuple** that are not comparable, *i.e.*, trigger a `TypeError` on comparison.

### To reproduce

```python
import signac

project = signac.init_project('type-comparison-issue')
for a in (0, None):
    project.open_job(dict(a=[a])).init()
print(project.detect_schema())
```
### Error output

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(project.detect_schema())
  File "/Users/csadorf/local/signac/signac/contrib/schema.py", line 134, in __str__
    return self.format()
  File "/Users/csadorf/local/signac/signac/contrib/schema.py", line 126, in format
    ret.append(" '{}': '{}',".format('.'.join(key), _fmt_values(values)))
  File "/Users/csadorf/local/signac/signac/contrib/schema.py", line 109, in _fmt_values
    return ', '.join(_fmt_range(*v) for v in values.items())
  File "/Users/csadorf/local/signac/signac/contrib/schema.py", line 109, in <genexpr>
    return ', '.join(_fmt_range(*v) for v in values.items())
  File "/Users/csadorf/local/signac/signac/contrib/schema.py", line 96, in _fmt_range
    sorted_values = sorted(values)
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: macOS
 - Version of Python [e.g. 3.7]: 3.7.2
 - Version of signac [e.g. 1.0]: *master*

**Comment by csadorf** [comment]
Fixed with merge of #210 .
