### ISSUE TITLE
Commas in project names cause unexpected errors

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#251]
### Description

I was creating a signac project named `oP6-As2(Co,Ni,Fe)_r`. This is problematic because the commas are not understood by the configuration parser.

### To reproduce

```python
>>> import signac
>>> signac.init_project('oP6-As2(Co,Ni,Fe)_r')
Traceback (most recent call last):
  File ".../signac/contrib/project.py", line 1462, in init_project
    project = cls.get_project(root=root, search=False)
  File ".../signac/contrib/project.py", line 1509, in get_project
    "Unable to determine project id for path '{}'.".format(os.path.abspath(root)))
LookupError: Unable to determine project id for path '/tmp_signac'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../signac/contrib/project.py", line 1867, in init_project
    return Project.init_project(name=name, root=root, workspace=workspace, make_dir=make_dir)
  File ".../signac/contrib/project.py", line 1472, in init_project
    assert project.get_id() == str(name)
AssertionError
```
or
```bash
$ signac init "oP6-As2(Co,Ni,Fe)_r"
Error:
```

In both cases, a file `signac.rc` is created with the contents:
```ini
project=oP6-As2(Co,Ni,Fe)_r
```

The project name is misinterpreted as a list:
```python
>>> project.get_id()
"['oP6-As2(Co', 'Ni', 'Fe)_r']"
```

### System configuration
 - Operating System: macOS
 - Version of Python: 3.7.3
 - Version of signac [e.g. 1.0]: 1.2.0 (running on latest `master`)

**Comment by bdice** [comment]
The configuration is created by hand, instead of using a `Config` or `ConfigObj` object. I suspect a similar problem could occur with workspace directories and other fields.

https://github.com/glotzerlab/signac/blob/38a31f96c91b8ebc3dc7674935c24b7ec0547bce/signac/contrib/project.py#L1461-L1467
