### ISSUE TITLE
Handle NumPy extended precision values.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac#383]
### Description

Related to #378 and #380. Currently it appears that signac is unable to transparently cast extended-precision NumPy values like `np.float128(9827389123.18237128)`.

I suggest the following:
1. Validators introduced in #378 should raise an error (and not accept extended-precision values as valid).
2. Tests of NumPy numeric types need to consider extended-precision values.

### To reproduce

```python
import numpy as np
import signac

doc = signac.JSONDict('test.json')
value = np.float128(1892739817.8127812)
doc.value = value
```

### Error output

A `RecursionError` is raised when attempting to call `value.item()` repeatedly (calling `value.item()` on an extended-precision value just returns itself, rather than a Python built-in type with an equivalent value): https://github.com/glotzerlab/signac/blob/7086d8981c926703a023654d1c59bbedcfae6298/signac/core/json.py#L28-L29

```pytb
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    doc.value = value
  File "/home/bdice/code/signac/signac/core/attrdict.py", line 42, in __setattr__
    self.__setitem__(key, value)
  File "/home/bdice/code/signac/signac/core/synceddict.py", line 200, in __setitem__
    self._synced_save()
  File "/home/bdice/code/signac/signac/core/synceddict.py", line 187, in _synced_save
    self.save()
  File "/home/bdice/code/signac/signac/core/synceddict.py", line 192, in save
    self._save()
  File "/home/bdice/code/signac/signac/core/jsondict.py", line 282, in _save
    blob = json.dumps(data).encode()
  File "/home/bdice/code/signac/signac/core/json.py", line 42, in dumps
    return CustomJSONEncoder(sort_keys=sort_keys, indent=indent).encode(o)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/bdice/miniconda3/envs/dice/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bdice/code/signac/signac/core/json.py", line 29, in default
    return o.item()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### System configuration

Please complete the following information:

 - Operating System: Ubuntu, AMD64
 - Version of Python: 3.8
 - Version of signac: 1.4.0

**Comment by bdice** [comment]
These functions might be helpful for detecting values that cannot be cast transparently to JSON-compatible types: https://numpy.org/doc/stable/reference/routines.dtype.html
